config/routes.rb
HowToSite::Application.routes.draw do
  root :to=> "tutorials#index"
  resources :tutorials do
    resources :steps
  end

end

app/models/step.rb
class Step < ActiveRecord::Base
  attr_accessible :description, :number, :tutorial_id

  belongs_to :tutorial
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  attr_accessible :description, :title

  has_many :steps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController

	before_filter :find_tutorial
	before_filter :find_step, :only => [:show, :edit, :update, :destroy]

	def new
		@step = @tutorial.steps.build
    respond_to do |format|
      format.html
      format.json {render json: @links}
    end
	end

	def edit
		@step = @tutorial.steps.find(params[:id])
	end

	def update
		if @step.update_attributes(params[:step])
			flash[:notice] = "Step has been updated."
			redirect_to @tutorial
		else
			flash[:alert] = "Step has not been updated."
			render :action => "edit"
		end
	end

	def create
		@step = @tutorial.steps.build(params[:step])
		if @step.save
			flash[:notice] = "Your step has been added."
			redirect_to @tutorial
		else
			flash[:notice] = "Your step has not been added."
			render :action => "new"
		end
	end

	private

	def find_tutorial
		@tutorial = Tutorial.find(params[:tutorial_id])
	end

	def find_step
		@step = @tutorial.steps.find(params[:id])
	end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController

	def new
		@tutorial = Tutorial.new
	end

	def edit
		@tutorial = Tutorial.find(params[:id])
	end

	def show
		@tutorial = Tutorial.find(params[:id])
	end

	def index
		@tutorials = Tutorial.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tutorials }
    end
	end

	def update
		@tutorial = Tutorial.find(params[:id])

    respond_to do |format|
      if @tutorial.update_attributes(params[:tutorial])
        format.html { redirect_to @tutorial, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
	end

	def create
		@tutorial = Tutorial.new(params[:tutorial])
		if @tutorial.save
			flash[:notice] = "Your Tutorial is ready to be created"
			redirect_to @tutorial
		else
			flash[:notice] = "Please, make sure all your fields are filled out correctly"
			render :action => "new"
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HowToSite" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><img src="https://www.codefellows.org/assets/CodeFellows-small-ff2a0932c27c0735f3344c0de4780693.png" id="headImg" /></a>
          <h1>Tutorials by Code Fellows</h1>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Do It!</h3>
              <p>Intelligence isn't what you know.
                What you know is knowledge.  Intelligence
                is the willingness and ability to learn.</p>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/steps/_form.html.erb
<%= form_for([@tutorial, @step]) do |f| %>
	<% if @step.errors.present? %>
	<%	@step.errors.full_message.each do |attribute, msg| %>
			<p><%= msg %></p>
		<% end %>
	<% end %>
	<table>
		<tr>
			<td>Description</td>
		</tr>
		<tr>
			<td><%= f.text_area :description, {:id=>'description'} %></td>
		</tr>
		<tr>
			<td><%= if @enter
								f.submit 'Edit'
							else
								f.submit 'Create'
							end %></td>
		</tr>
	</table>
<% end %>

app/views/steps/edit.html.erb
<% @edit = 'Edit' %>
<%= render "form" %>

app/views/steps/new.html.erb
<%= render "form" %>

app/views/tutorials/_form.html.erb
<%= form_for(@tutorial) do|f| %>
	<% if @tutorial.errors.full_messages.each do|msg| %>
		<p><%= msg %></p>
		<% end %>
	<% end %>
	<table>
		<tr>
			<td>Title</td>
		</tr>
		<tr>
			<td><%= f.text_field :title, {:id=>"title"} %></td>
		</tr>
		<tr>
			<td>Description</td>
		</tr>
		<tr>
			<td><%= f.text_area :description, {:id=>"description", :width=>300, :height=>400} %></td>
		</tr>
		<tr>
			<td><%= if @enter
								f.submit 'Edit'
							else
								f.submit 'Create'
							end %></td>
		</tr>
	</table>
<% end %>

app/views/tutorials/edit.html.erb
<% @enter = 'Edit' %>
<%= render "form" %>

app/views/tutorials/index.html.erb
<%= link_to "+ Tutorial", new_tutorial_path, {:class=>"btn fancybox", :float=>"right"} %>
	<% @tutorials.each do|tutorial| %>
	<div>
		<table class="table">
				<tr>
					<td><h2><%= link_to tutorial.title, tutorial %></h2></td>
				</tr>
				<tr>
					<td><%= tutorial.description %></td>
				</tr>
		</table>
	</div>
	<% end %>

app/views/tutorials/new.html.erb
<div id="fancyReturn">
	<%= render "form" %>
</div>

app/views/tutorials/show.html.erb
<h2><%= @tutorial.title %></h2>
<p><%= @tutorial.description %></p>
<% @counter = 1 %>
<%= link_to "Edit Tutorial", edit_tutorial_path(@tutorial), {:class=>"btn"} %>
<%= link_to "+ Steps", new_tutorial_step_path(@tutorial), {:class=>"btn"} %>
	<table class="table">
<% @tutorial.steps.each do |step| %>
		<tr>
			<td width="20"><b><%= @counter %>.</b></td>
			<td align="left"><%= step.description %></td>
			<td align="right"><%= link_to "Edit", [:edit, @tutorial, step ] %></td>
		</tr>
	<% @counter += 1 %>
<% end %>
	</table>